Squashed commit of the following:
commit 7ad8bfcb7421a2f88da1cfd28440506dd194c97a
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Fri Mar 15 16:40:22 2024 -0700

    update setup

commit 8cd3d6b6f905ed75e2246e33382ebc971f8af47c
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Fri Mar 15 15:19:36 2024 -0700

    update setup

commit 9d159a13b6470811c2b33dee647f167485e897c5
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Fri Mar 15 13:12:03 2024 -0700

    remove some files from PatchSource

commit 4115f6d32eb0a66ea56cda7ef4c4ac59420c233c
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Fri Mar 15 13:04:05 2024 -0700

    Update version

commit ec23a72c0bf04e53f739267a0f47873acc3acc58
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Fri Mar 15 13:03:33 2024 -0700

    Update setup

commit efe55b7737d4a9a0f165bc810c53093489e19854
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Fri Mar 15 12:49:29 2024 -0700

    Update version

commit a0e7c29d2182ea984061762f982cfb98e577a39a
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Fri Mar 15 12:46:07 2024 -0700

    remove v3.22 fileset

commit a38a94a5cde5f50311199b30259919804b834aa2
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Fri Mar 15 12:13:04 2024 -0700

    run packageUpdate

commit d58b89548ec0496f698a0de276e88bb5766f8234
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Fri Mar 15 12:08:53 2024 -0700

    add patch files

commit e8930997eb91f5542311a6c1273069817353b99d
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Fri Mar 15 11:59:02 2024 -0700

    change patch source filenames

commit 6ae30d2bdd78bc462ceb602c38add9601f624fd6
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Fri Mar 15 11:51:08 2024 -0700

    add patch files

commit 618c31116166ba90814b9403d781d43f4f049161
Merge: fc09794 0cdf755
Author: thomasinaz41213 <120696745+thomasinaz41213@users.noreply.github.com>
Date:   Fri Mar 15 10:15:34 2024 -0700

    Merge pull request #1 from thomasinaz41213/beta-3.0

    Create synctest

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -8,12 +8,19 @@
 
 packageLogFile="/var/log/RemoteGPIO/current"
 
-#### following lines incorporate SetupHelper utilities into this script
-# Refer to the SetupHelper ReadMe file for details.
-
-source "/data/SetupHelper/CommonResources"
-
-#### end of lines to include SetupHelper
+#### following lines incorporate helper resources into this script
+pkgDir=$( dirname $0 )
+pkgName=$( basename $pkgDir )
+pkgRoot=$( dirname $pkgDir )
+if [ -e "$pkgDir/HelperResources/IncludeHelpers" ]; then
+	source "$pkgDir/HelperResources/IncludeHelpers"
+elif [ -e "$pkgRoot/SetupHelper/HelperResources/IncludeHelpers" ]; then
+	source "$pkgRoot/SetupHelper/HelperResources/IncludeHelpers"
+else
+	echo "$pkgName: helper files not found - can't continue" | tee -a "/data/log/SetupHelper"
+	exit 1
+fi
+#### end of lines to include helper resources
 
 # GitHub account info - fill in as appropriate
 # to include this package in SetupHelper automatic updates
@@ -46,25 +53,28 @@ if [ $scriptAction == 'INSTALL' ] ; then
 	chmod 666 /data/RemoteGPIO/conf/units.conf
 	echo "0" > /data/RemoteGPIO/conf/units.conf
 
-	updateActiveFile /opt/victronenergy/dbus-systemcalc-py/delegates/relaystate.py 
-	updateActiveFile /etc/venus/gpio_list
-	updateActiveFile /etc/udev/rules.d/serial-starter.rules
+#	updateActiveFile /opt/victronenergy/dbus-systemcalc-py/delegates/relaystate.py 
+#	updateActiveFile /etc/venus/gpio_list
+#	updateActiveFile /etc/udev/rules.d/serial-starter.rules
 	
 	##
 	## For Large Image only with Node-Red support
 	#############################################
 	if [ $(dbus -y com.victronenergy.settings /Settings/System/ImageType GetValue) == 1 ]
 	then
-		updateActiveFile /usr/lib/node_modules/@victronenergy/node-red-contrib-victron/src/services/services.json
+
+		patch /usr/lib/node_modules/@victronenergy/node-red-contrib-victron/src/services/services.json /data/RemoteGPIO/FileSets/PatchSource/services.json.patchfile
+		
+		#updateActiveFile /usr/lib/node_modules/@victronenergy/node-red-contrib-victron/src/services/services.json
 	fi
 
 	##
 	## Install RemoteGPIO GUI Pages
 	###############################
-	updateActiveFile /opt/victronenergy/gui/qml/PageSettingsIo.qml
-	updateActiveFile /opt/victronenergy/gui/qml/PageSettingsRGPIO.qml 
-	updateActiveFile /opt/victronenergy/gui/qml/PageSettingsUnit1.qml
-	updateActiveFile /opt/victronenergy/gui/qml/PageSettingsUnit2.qml
+#	updateActiveFile /opt/victronenergy/gui/qml/PageSettingsIo.qml
+#	updateActiveFile /opt/victronenergy/gui/qml/PageSettingsRGPIO.qml 
+#	updateActiveFile /opt/victronenergy/gui/qml/PageSettingsUnit1.qml
+#	updateActiveFile /opt/victronenergy/gui/qml/PageSettingsUnit2.qml
 
 	##
 	## Create D-Bus entries for RemoteGPIO
@@ -112,16 +122,16 @@ if [ $scriptAction == 'UNINSTALL' ] ; then
 	svc -d /service/rgpio
 	kill $(ps | grep '{rgpio_service}' | grep -v grep | awk '{print $1}') 2>/dev/null
 	
-	restoreActiveFile /opt/victronenergy/dbus-systemcalc-py/delegates/relaystate.py 
-	restoreActiveFile /etc/venus/gpio_list
-	restoreActiveFile /etc/udev/rules.d/serial-starter.rules
-	restoreActiveFile /opt/victronenergy/gui/qml/PageSettingsIo.qml
+#	restoreActiveFile /opt/victronenergy/dbus-systemcalc-py/delegates/relaystate.py 
+#	restoreActiveFile /etc/venus/gpio_list
+#	restoreActiveFile /etc/udev/rules.d/serial-starter.rules
+#	restoreActiveFile /opt/victronenergy/gui/qml/PageSettingsIo.qml
 #	rm -f /opt/victronenergy/gui/qml/PageSettingsRGPIO.qml
 #	rm -f /opt/victronenergy/gui/qml/PageSettingsUnit1.qml
 #	rm -f /opt/victronenergy/gui/qml/PageSettingsUnit2.qml
-	restoreActiveFile /opt/victronenergy/gui/qml/PageSettingsRGPIO.qml
-	restoreActiveFile /opt/victronenergy/gui/qml/PageSettingsUnit1.qml
-	restoreActiveFile /opt/victronenergy/gui/qml/PageSettingsUnit2.qml
+# 	restoreActiveFile /opt/victronenergy/gui/qml/PageSettingsRGPIO.qml
+# 	restoreActiveFile /opt/victronenergy/gui/qml/PageSettingsUnit1.qml
+#	restoreActiveFile /opt/victronenergy/gui/qml/PageSettingsUnit2.qml
 	
 	rm -f /etc/rcS.d/S90rgpio_pins.sh
 
@@ -131,7 +141,9 @@ if [ $scriptAction == 'UNINSTALL' ] ; then
 	#############################################
 	if [ $(dbus -y com.victronenergy.settings /Settings/System/ImageType GetValue) == 1 ]
 	then
-		restoreActiveFile /usr/lib/node_modules/@victronenergy/node-red-contrib-victron/src/services/services.json
+		patch -R /usr/lib/node_modules/@victronenergy/node-red-contrib-victron/src/services/services.json /data/RemoteGPIO/FileSets/PatchSource/services.json.patchfile
+		
+		#restoreActiveFile /usr/lib/node_modules/@victronenergy/node-red-contrib-victron/src/services/services.json
 	fi
 
 
@@ -216,5 +228,5 @@ fi
 logMessage "completed"
 	
 # thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
-endScript
+endScript INSTALL_FILES
 
